linters:
  enable-all: true
  disable:
    - lll
    - gochecknoglobals
    - funlen
    - testpackage
    - gomnd
    - goerr113
    - wsl
    - gocognit

issues:
  exclude-use-default: false
  exclude:
    # Ignore missing documentation comments.
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # gosec: G304: Potential file inclusion via variable.
    - G304
